# Generated by Django 3.1.1 on 2020-09-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=60)),
                ('tz', models.CharField(max_length=60)),
                ('activity_periods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_api.activityperiod')),
            ],
        ),
    ]
