# Generated by Django 3.1.1 on 2020-09-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='ActivityPeriod',
            new_name='MemberActivity',
        ),
    ]
