# Generated by Django 3.1.1 on 2020-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_auto_20200926_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberactivity',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='memberactivity',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
